// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Blog = Collections['blogPosts']['schema']['_output']
export declare const blogPosts: Blog[]

export type Changelog = Collections['changelogItems']['schema']['_output']
export declare const changelogItems: Changelog[]
