import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
  keywords: ["sandip", "Sandip Gyawali", "sandipgyawali"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const composedClassName = `${geistSans.variable} ${geistMono.variable} antialiased`;

  return (
    <html lang="en" className={composedClassName}>
      <head>
        <link rel="icon" href="/logo.webp" sizes="any" />
      </head>
      <body suppressHydrationWarning>
        {children}
        <Toaster richColors closeButton position="bottom-right" />
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
        
        </ThemeProvider> */}
      </body>
    </html>
  );
}
